name: packer

on:
  push:
    branches: [ "main" ]

env:
  PRODUCT_VERSION: "1.8.7" # or: "latest"

jobs:
  packer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp/base

    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./base_docker.pkr.hcl"

#      - name: Run `packer build`
#        id: validate
#        run: "packer build ./base_docker.pkr.hcl"
